version: "3"

services:
  strapiexample:
    image: strapi/strapi
    container_name: strapiexample
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  mongoexample:
    image: mongo
    container_name: mongoexample
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    env_file: .env
    environment:
        ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
        DATABASE_NAME: ${DATABASE_NAME}
        ME_CONFIG_MONGODB_SERVER: ${DATABASE_HOST}
        ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME}
        ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD}
    networks:
        - strapi-app-network
    ports:
        - "8081:8081"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata: